name: Update wSH
on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Create Build Folder and Set Up Dependencies
      run: |
        mkdir wSH
        cd wSH
        wget https://github.com/copy/v86/releases/download/latest/libv86.js
        wget https://github.com/copy/v86/releases/download/latest/v86.wasm
        wget https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.8.0/lib/xterm-addon-fit.js
        wget https://cdn.jsdelivr.net/npm/xterm@5.3.0/lib/xterm.js
        wget https://cdn.jsdelivr.net/npm/xterm@5.3.0/css/xterm.css
        wget https://dl-cdn.alpinelinux.org/alpine/v3.24/releases/x86/alpine-virt-3.24.1-x86.iso -O alpine.iso
        wget https://github.com/copy/v86/raw/refs/heads/master/bios/vgabios.bin
        sudo apt install p7zip -y
        7z x alpine.iso
        mv boot/vmlinuz-virt .
        mv boot/initramfs-virt .
        git clone https://github.com/qemu/seabios
        cd seabios
        make defconfig
        cat << EOF >> .config
        # Option A: Debug Logging Configuration
        CONFIG_DEBUG_LEVEL=8
        CONFIG_DEBUG_SERIAL=y
        CONFIG_DEBUG_SERIAL_PORT=0x3f8

        # Option B: Interactive Serial Console (Sercon)
        CONFIG_SERCON=y
        EOF
        make olddefconfig
        make -j$(nproc)
        mv out/bios.bin ../seabios.bin

    - name: Create bundled.html
      run: |
        cd wSH
        cat << "EOF" > index.html
        <!DOCTYPE html>
        <html lang="en">
        <head>
        <meta charset="UTF-8">
        <meta
            name="viewport"
            content="width=device-width,initial-scale=1,maximum-scale=1,viewport-fit=cover,user-scalable=no">

        <title>Alpine Terminal</title>

        <link rel="stylesheet" href="xterm.css">

        <style>
        html,
        body {
            margin: 0;
            width: 100%;
            height: 100%;
            overflow: hidden;
            background: #000;
        }

        #terminal {
            position: fixed;
            inset: 0;
            width: 100vw;
            height: 100dvh;
            padding:
                env(safe-area-inset-top)
                env(safe-area-inset-right)
                env(safe-area-inset-bottom)
                env(safe-area-inset-left);
            box-sizing: border-box;
        }

        /* Hidden because we're using serial only */
        #screen_container {
            display: none;
        }
        </style>

        <script src="xterm.js"></script>
        <script src="xterm-addon-fit.js"></script>

        <script src="libv86.js"></script>
        </head>

        <body>

        <div id="terminal"></div>
        <div id="screen_container"></div>

        <script>
        const term = new Terminal({
            cursorBlink: true,
            convertEol: true,
            fontFamily: "monospace",
            fontSize: 16,
            scrollback: 10000
        });

        const fitAddon = new FitAddon.FitAddon();
        term.loadAddon(fitAddon);

        term.open(document.getElementById("terminal"));
        fitAddon.fit();

        const emulator = new V86({
            wasm_path: "v86.wasm",

            memory_size: 128 * 1024 * 1024,
            vga_memory_size: 8 * 1024 * 1024,

            // Hidden
            screen_container: document.getElementById("screen_container"),

            bios: {
                url: "seabios.bin"
            },

            vga_bios: {
                url: "vgabios.bin"
            },

            bzimage: {
                url: "vmlinuz-virt"
            },

            initrd: {
                url: "initramfs-virt"
            },

            cdrom: {
                url: "alpine.iso"
            },

            cmdline:
                "console=ttyS0,115200 " +
                "earlyprintk=serial,ttyS0,115200 " +
                "loglevel=7",

            autostart: true
        });

        // Receive serial data
        function writeByte(b)
        {
            term.write(String.fromCharCode(b));
        }

        if (emulator.add_listener)
        {
            emulator.add_listener("serial0-output-byte", writeByte);

            emulator.add_listener("serial0-output-char", function(c)
            {
                term.write(c);
            });

            emulator.add_listener("serial0-output-line", function(line)
            {
                term.writeln(line);
            });
        }

        // Send keyboard input back to serial
        term.onData(function(data)
        {
            emulator.serial0_send(data);
        });

        function resizeTerminal()
        {
            fitAddon.fit();
        }

        window.addEventListener("resize", resizeTerminal);
        window.addEventListener("orientationchange", function()
        {
            setTimeout(resizeTerminal, 100);
        });

        window.addEventListener("focus", function()
        {
            term.focus();
        });

        term.focus();

        if ("serviceWorker" in navigator) {
            navigator.serviceWorker.register("sw.js");
        }
        </script>

        </body>
        </html>
        EOF

    - name: Create Service Worker
      run: |
        cd wSH
        cat << "EOF" > sw.js
        const CACHE = "v86-offline-v1";

        const FILES = [
            "./",
            "./index.html",

            "./libv86.js",
            "./v86.wasm",

            "./seabios.bin",
            "./vgabios.bin",

            "./vmlinuz-virt",
            "./initramfs-virt",
            "./alpine.iso",

            "./xterm.js",
            "./xterm.css",
            "./xterm-addon-fit.js"
        ];

        self.addEventListener("install", event => {
            event.waitUntil(
                caches.open(CACHE).then(cache => cache.addAll(FILES))
            );
            self.skipWaiting();
        });

        self.addEventListener("activate", event => {
            event.waitUntil(clients.claim());
        });

        self.addEventListener("fetch", event => {
            event.respondWith(
                caches.match(event.request).then(response => {
                    return response || fetch(event.request);
                })
            );
        });
        EOF

    - name: Bundle & Patch bundled.html
      run: |
        #cd wSH
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "libv86.js"; $mime = "text/javascript"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "v86.wasm"; $mime = "application/wasm"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "seabios.bin"; $mime = "application/octet-stream"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "vgabios.bin"; $mime = "application/octet-stream"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "xterm.js"; $mime = "text/javascript"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "xterm.css"; $mime = "text/css"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "xterm-addon-fit.js"; $mime = "text/javascript"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "alpine.iso"; $mime = "application/octet-stream"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "vmlinuz-virt"; $mime = "application/octet-stream"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html
        #perl -MMIME::Base64 -i -pe 'BEGIN { $file = "initramfs-virt"; $mime = "application/octet-stream"; open my $fh, "<:raw", $file or die "Missing $file: $!"; local $/; $b64 = encode_base64(<$fh>, ""); $uri = "data:$mime;base64,$b64"; } s/\b\Q$file\E\b/$uri/g' bundled.html

    - name: Replace Old index.html File
      run: |
        #[[ -f server/index.html ]] && rm server/index.html
        #mv wSH/bundled.html server/index.html
        rm -r server
        mkdir server
        mv wSH/index.html server/
        mv wSH/*.js server/
        mv wSH/*.bin server/
        mv wSH/*-virt server/
        mv wSH/alpine.iso server/
        mv wSH/xterm.css server/
        mv wSH/v86.wasm server/

    - name: Update Icon Data
      run: |
        python -c "import base64,re; d=base64.b64encode(open('assets/appicon.png','rb').read()).decode(); f='unsigned.mobileconfig'; s=open(f,'r',encoding='utf-8').read(); s=re.sub(r'      <data>.*</data>', f'      <data>{d}</data>', s); open(f,'w',encoding='utf-8').write(s)"

    # 4. Commit and overwrite the root file
    - name: Commit
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add unsigned.mobileconfig
        #git add server/index.html
        git add server
        git commit -m "Automated update: Updated unsigned Mobileconfig and wSH HTML" || echo "No changes to commit"
        git push
